### ISSUE TITLE
Dataset isn't extracting. 

### ISSUE THREAD

**Issue by aiguo112** [simula/kvasir-capsule#1]
Dataset provided [here](https://osf.io/dv2ag/) is not extracting. 
![Screenshot_1](https://user-images.githubusercontent.com/81693706/137571215-1195a882-0afd-418d-b4db-3b8101ac6b4f.png)

**Comment by YossiZhao** [comment]
I also cannot open the dataset, did you solve the problem?

**Comment by aiguo112** [comment]
No, I couldn't come up with a solution.

**Comment by franciszchen** [comment]
Same problem in Linux.

**Comment by kelkalot** [comment]
The problem comes from OSF. All data is also available here: https://drive.google.com/drive/u/1/folders/18vEHN1CG7oNFKdT2NmhtJjrFhb3tLG1Z and here https://datasets.simula.no/kvasir-capsule/ as zip file.
